from random import choice, randint

words = [
    "apple",
    "banana",
    "car",
    "dog",
    "elephant",
    "forest",
    "garden",
    "house",
    "island",
    "jungle",
    "kitchen",
    "lamp",
    "mountain",
    "notebook",
    "ocean",
    "piano",
    "queen",
    "river",
    "sun",
    "tree",
    "umbrella",
    "village",
    "window",
    "xylophone",
    "yellow",
    "zebra",
    "airplane",
    "bridge",
    "castle",
    "dragon",
    "eagle",
    "flower",
    "galaxy",
    "hammer",
    "iceberg",
    "jacket",
    "kite",
    "lemon",
    "mirror",
    "nest",
    "orange",
    "penguin",
    "quartz",
    "rocket",
    "snake",
    "tiger",
    "unicorn",
    "volcano",
    "whale",
    "basket",
    "candle",
    "diamond",
    "engine",
    "feather",
    "guitar",
    "honey",
    "igloo",
    "jigsaw",
    "kernel",
    "ladder",
    "marble",
    "needle",
    "octopus",
    "parrot",
    "pillow",
    "rain",
    "snow",
    "thunder",
    "valley",
    "water",
    "cloud",
    "stone",
    "metal",
    "paper",
    "glass",
    "copper",
    "silver",
    "gold",
    "bronze",
    "iron",
    "steel",
    "carbon",
    "nitrogen",
    "oxygen",
    "hydrogen",
    "helium",
    "neon",
    "argon",
    "sodium",
    "calcium",
    "potassium",
    "magnesium",
    "aluminum",
    "silicon",
    "phosphorus",
    "sulfur",
    "chlorine",
    "bromine",
    "iodine",
    "lithium",
    "beryllium",
    "boron",
    "fluorine",
    "titanium",
    "chromium",
    "manganese",
    "cobalt",
    "nickel",
    "zinc",
    "arsenic",
    "selenium",
    "rubidium",
    "strontium",
    "planet",
    "star",
    "comet",
    "asteroid",
    "nebula",
    "quasar",
    "pulsar",
    "orbit",
    "gravity",
    "photon",
    "electron",
    "proton",
    "neutron",
    "atom",
    "molecule",
    "crystal",
    "mineral",
    "fossil",
    "glacier",
    "canyon",
    "desert",
    "savanna",
    "tundra",
    "wetland",
    "coral",
    "reef",
    "lagoon",
    "delta",
    "plateau",
    "cliff",
    "dune",
    "meadow",
    "prairie",
    "swamp",
    "marsh",
    "harbor",
    "peninsula",
    "archipelago",
    "continent",
    "equator",
    "tropics",
    "prism",
    "spectrum",
    "wavelength",
    "frequency",
    "amplitude",
    "resonance",
    "velocity",
    "momentum",
    "inertia",
    "friction",
    "tension",
    "pressure",
    "density",
    "volume",
    "capacity",
    "threshold",
    "amplifier",
    "conductor",
    "insulator",
    "catalyst",
    "reagent",
    "solvent",
    "solution",
    "compound",
    "polymer",
    "crystal",
    "lattice",
    "matrix",
    "vector",
    "scalar",
    "tensor",
    "algorithm",
    "function",
    "variable",
    "constant",
    "parameter",
    "operator",
    "index",
    "array",
    "sequence",
    "iterator",
    "callback",
    "prototype",
    "instance",
    "module",
    "library",
    "framework",
    "compiler",
    "runtime",
    "thread",
    "process",
    "socket",
    "buffer",
    "cache",
    "registry",
    "pipeline",
    "bridge",
    "tunnel",
    "highway",
    "boulevard",
    "avenue",
    "lane",
    "alley",
    "plaza",
    "tower",
    "dome",
    "arch",
    "pillar",
    "column",
    "beam",
    "rafter",
    "compass",
    "chronicle",
    "legend",
    "myth",
    "saga",
    "tale",
    "fable",
    "parable",
    "riddle",
    "enigma",
    "cipher",
    "code",
    "symbol",
    "glyph",
    "script",
    "manuscript",
    "scroll",
    "tome",
    "atlas",
    "codex",
    "folio",
    "chapter",
    "verse",
    "stanza",
    "hymn",
    "ballad",
    "sonnet",
    "epic",
    "anthem",
    "requiem",
    "nocturne",
    "prelude",
    "fugue",
    "suite",
    "overture",
    "ballet",
    "opera",
    "sonata",
    "concerto",
    "symphony",
    "waltz",
    "march",
    "cathedral",
    "monastery",
    "temple",
    "shrine",
    "altar",
    "sanctuary",
    "bazaar",
    "market",
    "auction",
    "trade",
    "craft",
    "guild",
    "workshop",
    "forger",
    "smith",
    "mason",
    "carpenter",
    "weaver",
    "potter",
    "glazier",
    "journey",
    "voyage",
    "expedition",
    "pilgrimage",
    "odyssey",
    "trek",
    "compass",
    "sextant",
    "astrolabe",
    "telescope",
    "microscope",
    "prism",
    "pendulum",
    "barometer",
    "thermometer",
    "chronometer",
    "compass",
    "key",
    "lock",
    "door",
    "gate",
    "fence",
    "wall",
    "roof",
    "floor",
    "ceiling",
    "stairs",
    "hall",
    "corridor",
    "chamber",
    "vault",
    "crypt",
]
phrases = [
    "the quick brown fox jumps over the lazy dog",
    "a stitch in time saves nine",
    "every cloud has a silver lining",
    "the early bird catches the worm",
    "actions speak louder than words",
    "all that glitters is not gold",
    "beauty is in the eye of the beholder",
    "curiosity killed the cat",
    "don't count your chickens before they hatch",
    "fortune favors the bold",
    "knowledge is power",
    "practice makes perfect",
    "time heals all wounds",
    "where there's smoke there's fire",
    "you can't judge a book by its cover",
    "the pen is mightier than the sword",
    "when in Rome do as the Romans do",
    "two wrongs don't make a right",
    "the grass is always greener on the other side",
    "easy come easy go",
    "haste makes waste",
    "if it ain't broke don't fix it",
    "you reap what you sow",
    "every dog has its day",
    "the road to hell is paved with good intentions",
    "necessity is the mother of invention",
    "people who live in glass houses shouldn't throw stones",
    "a picture is worth a thousand words",
    "there's no such thing as a free lunch",
    "silence is golden",
    "the truth will set you free",
    "birds of a feather flock together",
    "absence makes the heart grow fonder",
    "familiarity breeds contempt",
    "it takes two to tango",
    "hope for the best prepare for the worst",
    "better late than never",
    "two heads are better than one",
    "the apple doesn't fall far from the tree",
    "still waters run deep",
    "don't put all your eggs in one basket",
    "a watched pot never boils",
    "too many cooks spoil the broth",
    "opposites attract",
    "money doesn't grow on trees",
    "the best things in life are free",
    "good things come to those who wait",
    "nice guys finish last",
    "cheaters never prosper",
    "look before you leap",
    "the squeaky wheel gets the grease",
    "it's always darkest before the dawn",
    "you can't teach an old dog new tricks",
    "cleanliness is next to godliness",
    "the whole is greater than the sum of its parts",
    "what doesn't kill you makes you stronger",
    "a rolling stone gathers no moss",
    "lightning never strikes the same place twice",
    "the root of all evil is the love of money",
    "patience is a virtue",
    "an ounce of prevention is worth a pound of cure",
    "he who hesitates is lost",
    "the only constant in life is change",
    "there is no such thing as bad publicity",
    "absolute power corrupts absolutely",
    "history repeats itself",
    "the end justifies the means",
    "give a man a fish and you feed him for a day",
    "teach a man to fish and you feed him for a lifetime",
    "all roads lead to Rome",
    "behind every great man is a great woman",
    "the pen is mightier than the sword",
    "discretion is the better part of valor",
    "genius is one percent inspiration and ninety-nine percent perspiration",
    "nothing ventured nothing gained",
    "the spirit is willing but the flesh is weak",
    "all work and no play makes Jack a dull boy",
    "a chain is only as strong as its weakest link",
    "the proof of the pudding is in the eating",
    "great minds think alike",
    "a bird in the hand is worth two in the bush",
    "out of sight out of mind",
    "a leopard cannot change its spots",
    "the boy who cried wolf",
    "don't bite the hand that feeds you",
    "all good things must come to an end",
    "necessity knows no law",
    "the darkest hour is just before the dawn",
    "there's a time and a place for everything",
    "what goes around comes around",
    "the moon is made of green cheese",
    "every man has his price",
    "the tail wags the dog",
    "the emperor has no clothes",
    "water under the bridge",
    "a wolf in sheep's clothing",
    "between a rock and a hard place",
    "burning the midnight oil",
    "caught red-handed",
    "the ball is in your court",
    "bite the bullet",
    "break the ice",
    "hit the nail on the head",
    "kick the bucket",
    "let the cat out of the bag",
    "piece of cake",
    "spill the beans",
    "take it with a grain of salt",
    "the best of both worlds",
    "throw caution to the wind",
    "under the weather",
    "when pigs fly",
    "wrap your head around it",
    "cut corners",
    "devil's advocate",
    "elephant in the room",
    "last straw",
    "on thin ice",
    "up in the air",
    "beat around the bush",
    "blessing in disguise",
    "once in a blue moon",
    "a penny for your thoughts",
    "back to the drawing board",
    "call it a day",
    "cut to the chase",
    "hang in there",
    "no pain no gain",
    "on the ball",
    "pull someone's leg",
    "so far so good",
    "the sky is the limit",
    "time flies when you're having fun",
    "your guess is as good as mine",
    "a snowball effect in global markets",
    "the development of quantum computing technology",
    "sustainable agriculture practices in tropical regions",
    "the impact of social media on modern communication",
    "advances in artificial intelligence and machine learning",
    "the exploration of deep-sea ecosystems",
    "renewable energy solutions for urban environments",
    "the history of ancient civilizations and their contributions",
    "biodiversity conservation in coral reef systems",
    "the role of education in economic development",
    "geothermal energy production in volcanic regions",
    "the psychology of decision making under uncertainty",
    "nano materials and their applications in engineering",
    "the influence of classical philosophy on modern thought",
    "population dynamics in urban and rural settings",
    "the intersection of art and technology in the digital age",
    "cognitive biases in human perception and reasoning",
    "the evolution of programming languages over decades",
    "climate modeling and long-term weather prediction",
    "the social implications of autonomous vehicle technology",
    "genetic engineering and its impact on agriculture",
    "the cultural significance of traditional music worldwide",
    "blockchain technology beyond cryptocurrency applications",
    "the neuroscience of creativity and innovation",
    "space debris mitigation and orbital sustainability",
    "the economics of renewable resource management",
    "archaeological discoveries reshaping historical timelines",
    "the role of microbiomes in human health and disease",
    "photovoltaic efficiency improvements in solar panels",
    "the linguistic evolution of Indo-European language families",
    "cybersecurity challenges in the era of IoT devices",
    "the sociological impact of remote work culture",
    "CRISPR gene editing and therapeutic applications",
    "the philosophical implications of consciousness studies",
    "vertical farming and urban food production systems",
    "the mathematics of fractal geometry in nature",
    "cross-cultural communication in globalized business",
    "the thermodynamics of black hole information paradox",
    "bio-mimicry in sustainable architecture and design",
    "the anthropology of ritual and ceremony across cultures",
    "quantum entanglement and its implications for computing",
    "the economic impact of an aging global population",
    "machine translation and the preservation of endangered languages",
    "the ecological consequences of deforestation in the Amazon",
    "neuroplasticity and rehabilitation after brain injury",
    "the relationship between sleep patterns and cognitive performance",
    "exoplanet detection methods and habitability assessment",
    "supply chain resilience in global manufacturing networks",
]

random_num = "8913890231"

# in chars.
file_length = 100_000

before = ""
after = ""


needle_pos = randint(int(0.4 * file_length), int(0.6 * file_length))

while len(before) <= needle_pos:
    before += choice([choice(words), choice(phrases)])

while len(after) + len(before) <= file_length:
    after += choice([choice(words), choice(phrases)])

with open("./example/NIAH", "w") as f:
    f.write(before + random_num + after)
